-- Creacion del tablespace
CREATE TABLESPACE ELECCIONESTBS DATAFILE 'ELECCIONESDTF.tbs' 
	SIZE 250m
	AUTOEXTEND ON MAXSIZE 500m;

-- Creacion del schema
ALTER SESSION SET "_ORACLE_SCRIPT" = true;
CREATE USER elecciones
	IDENTIFIED BY elecciones
	PROFILE DEFAULT
	DEFAULT TABLESPACE eleccionestbs
	TEMPORARY TABLESPACE temp
	ACCOUNT unlock;


-- Permisos del usuario
GRANT DBA TO elecciones WITH ADMIN OPTION;
GRANT ALTER SESSION TO elecciones WITH ADMIN OPTION;

-- Configuraciones de la base de datos
ALTER SYSTEM SET pga_aggregate_target = 100m;
ALTER SYSTEM SET sga_target = 512m;
ALTER SYSTEM SET sessions = 500 scope = spfile;
ALTER SYSTEM SET processes = 320 scope = spfile;

SHOW PARAMETER sga_;
SHOW PARAMETER pga_;
SHOW PARAMETER sessions;
SHOW PARAMETER processes;

-- Creacion de vista
CREATE VIEW VOTOSPRESIDENTE(
	Departamento,
	Municipio,
	Partido,
	Votos
) AS
SELECT
	ELECCIONES.DEPARTAMENTO.NOMBRE_DEPTO,
	ELECCIONES.MUNICIPIO.NOMBRE_MUNI,
	ELECCIONES.PARTIDO.NOMBRE_PART,
	SUM(ELECCIONES.VOTO.VOTO_CANTIDAD)
FROM
	ELECCIONES.DEPARTAMENTO,
	ELECCIONES.MUNICIPIO,
	ELECCIONES.PARTIDO,
	ELECCIONES.ACTA,
	ELECCIONES.VOTO
WHERE
	ELECCIONES.ACTA.NUMERO_MESA = ELECCIONES.VOTO.VOTO_MESA AND
	ELECCIONES.ACTA.MUNICIPIO = ELECCIONES.MUNICIPIO.CODIGO_MUNI AND
	ELECCIONES.MUNICIPIO.DEPTO_MUNI = ELECCIONES.DEPARTAMENTO.CODIGO_DEPTO
GROUP BY
	ELECCIONES.DEPARTAMENTO.NOMBRE_DEPTO, 
	ELECCIONES.MUNICIPIO.NOMBRE_MUNI,
	ELECCIONES.PARTIDO.NOMBRE_PART;


-- Crearcion de usuarios
---- Guest
CREATE USER guest1 PROFILE DEFAULT IDENTIFIED BY guest1 DEFAULT TABLESPACE ELECCIONESTBS TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;
GRANT SELECT ON ELECCIONES.DEPARTAMENTO TO guest1;
GRANT SELECT ON ELECCIONES.MUNICIPIO TO guest1;
GRANT SELECT ON ELECCIONES.PARTIDO TO guest1;
GRANT SELECT ON ELECCIONES.ELECCION TO guest1;
GRANT SELECT ON ELECCIONES.ACTA TO guest1;
GRANT SELECT ON ELECCIONES.VOTO TO guest1;
GRANT SELECT ON ELECCIONES.VOTOSPRESIDENTE TO guest1;
GRANT CREATE SESSION TO guest1;

CREATE USER guest2 PROFILE DEFAULT IDENTIFIED BY guest2 DEFAULT TABLESPACE ELECCIONESTBS TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;
GRANT SELECT ON DEPARTAMENTO TO guest2;
GRANT SELECT ON MUNICIPIO TO guest2;
GRANT SELECT ON PARTIDO TO guest2;
GRANT SELECT ON ELECCION TO guest2;
GRANT SELECT ON ACTA TO guest2;
GRANT SELECT ON VOTO TO guest2;
GRANT SELECT ON VOTOSPRESIDENTE TO guest2;
GRANT CREATE SESSION TO guest2;

CREATE USER guest3 PROFILE DEFAULT IDENTIFIED BY guest3 DEFAULT TABLESPACE ELECCIONESTBS TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;
GRANT SELECT ON DEPARTAMENTO TO guest3;
GRANT SELECT ON MUNICIPIO TO guest3;
GRANT SELECT ON PARTIDO TO guest3;
GRANT SELECT ON ELECCION TO guest3;
GRANT SELECT ON ACTA TO guest3;
GRANT SELECT ON VOTO TO guest3;
GRANT SELECT ON VOTOSPRESIDENTE TO guest3;
GRANT CREATE SESSION TO guest3;

---- Mesas
CREATE USER mesas1 PROFILE DEFAULT IDENTIFIED BY mesas1 DEFAULT TABLESPACE ELECCIONESTBS TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;
GRANT SELECT, INSERT ON DEPARTAMENTO TO mesas1;
GRANT SELECT, INSERT ON MUNICIPIO TO mesas1;
GRANT SELECT, INSERT ON PARTIDO TO mesas1;
GRANT SELECT, INSERT ON ELECCION TO mesas1;
GRANT SELECT, INSERT ON ACTA TO mesas1;
GRANT SELECT, INSERT ON VOTO TO mesas1;
GRANT SELECT, INSERT ON VOTOSPRESIDENTE TO mesas1;
GRANT CREATE SESSION TO mesas1;

CREATE USER mesas2 PROFILE DEFAULT IDENTIFIED BY mesas2 DEFAULT TABLESPACE ELECCIONESTBS TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;
GRANT SELECT, INSERT ON DEPARTAMENTO TO mesas2;
GRANT SELECT, INSERT ON MUNICIPIO TO mesas2;
GRANT SELECT, INSERT ON PARTIDO TO mesas2;
GRANT SELECT, INSERT ON ELECCION TO mesas2;
GRANT SELECT, INSERT ON ACTA TO mesas2;
GRANT SELECT, INSERT ON VOTO TO mesas2;
GRANT SELECT, INSERT ON VOTOSPRESIDENTE TO mesas2;
GRANT CREATE SESSION TO mesas2;

CREATE USER mesas3 PROFILE DEFAULT IDENTIFIED BY mesas3 DEFAULT TABLESPACE ELECCIONESTBS TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;
GRANT SELECT, INSERT ON DEPARTAMENTO TO mesas3;
GRANT SELECT, INSERT ON MUNICIPIO TO mesas3;
GRANT SELECT, INSERT ON PARTIDO TO mesas3;
GRANT SELECT, INSERT ON ELECCION TO mesas3;
GRANT SELECT, INSERT ON ACTA TO mesas3;
GRANT SELECT, INSERT ON VOTO TO mesas3;
GRANT SELECT, INSERT ON VOTOSPRESIDENTE TO mesas3;
GRANT CREATE SESSION TO mesas3;

CREATE USER mesas4 PROFILE DEFAULT IDENTIFIED BY mesas4 DEFAULT TABLESPACE ELECCIONESTBS TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;
GRANT SELECT, INSERT ON DEPARTAMENTO TO mesas4;
GRANT SELECT, INSERT ON MUNICIPIO TO mesas4;
GRANT SELECT, INSERT ON PARTIDO TO mesas4;
GRANT SELECT, INSERT ON ELECCION TO mesas4;
GRANT SELECT, INSERT ON ACTA TO mesas4;
GRANT SELECT, INSERT ON VOTO TO mesas4;
GRANT SELECT, INSERT ON VOTOSPRESIDENTE TO mesas4;
GRANT CREATE SESSION TO mesas4;

---- IT
CREATE USER it1 PROFILE DEFAULT IDENTIFIED BY it1 DEFAULT TABLESPACE ELECCIONESTBS TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;
GRANT SELECT ON DEPARTAMENTO TO it1;
GRANT SELECT ON MUNICIPIO TO it1;
GRANT SELECT ON PARTIDO TO it1;
GRANT SELECT ON ELECCION TO it1;
GRANT SELECT ON ACTA TO it1;
GRANT SELECT ON VOTO TO it1;
GRANT SELECT ON VOTOSPRESIDENTE TO it1;
GRANT CREATE USER, CREATE TABLE TO it1;
GRANT CREATE SESSION TO it1;

CREATE USER it2 PROFILE DEFAULT IDENTIFIED BY it2 DEFAULT TABLESPACE ELECCIONESTBS TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;
GRANT SELECT ON DEPARTAMENTO TO it2;
GRANT SELECT ON MUNICIPIO TO it2;
GRANT SELECT ON PARTIDO TO it2;
GRANT SELECT ON ELECCION TO it2;
GRANT SELECT ON ACTA TO it2;
GRANT SELECT ON VOTO TO it2;
GRANT SELECT ON VOTOSPRESIDENTE TO it2;
GRANT CREATE USER, CREATE TABLE TO it2;
GRANT CREATE SESSION TO it2;

CREATE USER it3 PROFILE DEFAULT IDENTIFIED BY it3 DEFAULT TABLESPACE ELECCIONESTBS TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;
GRANT SELECT ON DEPARTAMENTO TO it3;
GRANT SELECT ON MUNICIPIO TO it3;
GRANT SELECT ON PARTIDO TO it3;
GRANT SELECT ON ELECCION TO it3;
GRANT SELECT ON ACTA TO it3;
GRANT SELECT ON VOTO TO it3;
GRANT SELECT ON VOTOSPRESIDENTE TO it3;
GRANT CREATE USER, CREATE TABLE TO it3;
GRANT CREATE SESSION TO it3;

---- Admin
CREATE USER admin1 PROFILE DEFAULT IDENTIFIED BY admin1 DEFAULT TABLESPACE ELECCIONESTBS TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;
GRANT UPDATE, INSERT, SELECT, DELETE ON DEPARTAMENTO TO admin1;
GRANT UPDATE, INSERT, SELECT, DELETE ON MUNICIPIO TO admin1;
GRANT UPDATE, INSERT, SELECT, DELETE ON PARTIDO TO admin1;
GRANT UPDATE, INSERT, SELECT, DELETE ON ELECCION TO admin1;
GRANT UPDATE, INSERT, SELECT, DELETE ON ACTA TO admin1;
GRANT UPDATE, INSERT, SELECT, DELETE ON VOTO TO admin1;
GRANT UPDATE, INSERT, SELECT, DELETE ON VOTOSPRESIDENTE TO admin1;
GRANT CREATE USER TO admin1;
GRANT CREATE SESSION TO admin1;

CREATE USER admin2 PROFILE DEFAULT IDENTIFIED BY admin2 DEFAULT TABLESPACE ELECCIONESTBS TEMPORARY TABLESPACE TEMP ACCOUNT UNLOCK;
GRANT UPDATE, INSERT, SELECT, DELETE ON DEPARTAMENTO TO admin2;
GRANT UPDATE, INSERT, SELECT, DELETE ON MUNICIPIO TO admin2;
GRANT UPDATE, INSERT, SELECT, DELETE ON PARTIDO TO admin2;
GRANT UPDATE, INSERT, SELECT, DELETE ON ELECCION TO admin2;
GRANT UPDATE, INSERT, SELECT, DELETE ON ACTA TO admin2;
GRANT UPDATE, INSERT, SELECT, DELETE ON VOTO TO admin2;
GRANT UPDATE, INSERT, SELECT, DELETE ON VOTOSPRESIDENTE TO admin2;
GRANT CREATE USER TO admin2;
GRANT CREATE SESSION TO admin2;


-- Pruebas de insercion
---- Error en Guest, Mesas, It
DELETE FROM ELECCIONES.VOTO;

---- Error en Admin
CREATE TABLE Prueba(
	ID NUMBER NOT NULL
);
